spring:
  application:
    name: ${NOMBRE_MICROSERVICIO:structure-microservice}
  data:
    mongodb:
      uri: mongodb+srv://victor2025:victor2025@cluster0.w1ywt.mongodb.net/zona?retryWrites=true&w=majority&appName=Cluster0

  web:
    resources:
      cache:
        period: 0

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API V1
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  paths-to-match: /api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

app:
  name: Structure Microservice
  description: Microservicio para gestión de estructuras
  version: 1.0.0